import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Header from "~/components/Header";
import { Irish_Grover } from 'next/font/google';
import { Inter } from 'next/font/google';
import Footer from "~/components/Footer";
import MyQueryClientProvider from "../components/MyQueryClientProvider";
import { Toaster } from 'react-hot-toast'

const irishGrover = Irish_Grover({
  weight: '400',  
  subsets: ['latin'],      
});

const inter = Inter({
  subsets: ['latin'], 
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "HOTEL",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.className} ${irishGrover.className} ${GeistSans.variable}`}>
      <body>
      <MyQueryClientProvider>
        <Header/>
        <Toaster position="top-center" />
        {children}
        <Footer/>
      </MyQueryClientProvider>
      </body>
    </html>
  );
}
